### PR TITLE
Add support for Foundry 12

### PR DESCRIPTION
**Pull request by Opeey**
Hi, i patched the Drag Upload Module to be compatible with Foundry 12.
I tested everything with Foundry 9, 10, 11 and 12 and everything seemed to work fine.

I would be happy if you could merge the changes, so that the plugin can be updated for everyone via Foundry.

### CODE REVIEW

**Comment by LeRatierBretonnien** [comment]
Is there plan to update this for v12 ?

**Comment by Opeey** [comment]
Hi @LeRatierBretonnien.
It seems like the author of this repository @amir-arad does not maintain their repository currently.
The changes i proposed here, add support for foundry 12. Maybe @amir-arad wants to merge those at some point. In the meantime you can install my version in foundry via the URL:
https://github.com/Opeey/FoundryVTT-Drag-Upload/releases/download/2.3.1/module.json if you want.

**Comment by LeRatierBretonnien** [comment]
Thanks ! I was planning to fork it myself and to apply your patch :)
Note that if @amir-arad does not respond anymore, we can contact the Foundry team to point to your repository.

**Comment by amir-arad** [comment]
hi
sorry I was away. will look into this in a few days.

**Comment by Tyberius2303** [comment]
Just wondering if there has been any update on this at all?
Been having an issue where the weather blocker now no longer blocks out the weather and has to be reapplied each time I switch scene's.

**Comment by amir-arad** [comment]
Sadly I can't find the time to maintain this module. 
@Opeey would you mind taking over custody of it from me? 
I've "inherited" it under similar circumstances

**Comment by Opeey** [comment]
Hi @amir-arad, i've also not that much time on my hands.
But i am at least currently using the module actively.

So i can take over, to maintain the compatiblity to foundry for a while :)

**Comment by amir-arad** [comment]
@Opeey invited

**Comment by LeRatierBretonnien** [comment]
If you need help also, I can participate and push PR (or help to maintain the releases) :)

**Pull request merged**
